name: Yellow Feather
favicon: null
layout_spectrum: 0.7869164268486202
typography_spectrum: 0.56694
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#151714'
    - '#fcfcfc'
    - '#cecfd3'
    - '#959186'
    - '#765e39'
  brandStrength: 0.625
  lightness: 0.9375
  saturation: 0.5862218379043043
  rhythmicContrast: 0.5
purpose: []
