name: Yellow Feather
favicon: null
layout_spectrum: 0.7869164268486202
typography_spectrum: 0.56694
title: Photography Ramblings
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e4dee0'
    - '#1f2022'
    - '#bbb8c1'
    - '#5d8390'
    - '#8e6521'
  brandStrength: 0.625
  lightness: 0.9375
  saturation: 0.5862218379043043
  rhythmicContrast: 0.5
purpose: []
